version: '3.8'

services:
  warp:
    image: caomingjun/warp
    container_name: warp-proxy
    restart: unless-stopped
    environment:
      - WARP_SLEEP=2
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    device_cgroup_rules:
      - 'c 10:200 rwm'
    healthcheck:
      test: ["CMD", "curl", "-f", "--proxy", "socks5://localhost:1080", "http://www.google.com", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  stream-extractor:
    build: .
    container_name: stream-extractor
    restart: unless-stopped
    depends_on:
      warp:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./streams.txt:/app/streams.txt
    environment:
      - TZ=UTC
    command: >
      sh -c "while true; do
        python stream_extractor.py --proxy warp:1080;
        sleep 600;
      done"
